import { promises as fs } from 'node:fs';
import path from 'node:path';
import readline from 'node:readline/promises';
import { stdin, stdout } from 'node:process';

export type SetupProvider = 'vertex' | 'anthropic' | 'openai' | 'bedrock';

export interface VertexSetup { provider: 'vertex'; project: string; location: string; model: string; credentialsPath: string }
export interface AnthropicSetup { provider: 'anthropic'; apiKey: string; model?: string }
export interface OpenAISetup { provider: 'openai'; apiKey: string; model?: string }
export interface BedrockSetup { provider: 'bedrock'; region: string; modelId: string }
export type SetupConfig = VertexSetup | AnthropicSetup | OpenAISetup | BedrockSetup;

/**
 * Validate a service-account JSON string. Returns the non-secret identifiers.
 * Throws with a clear message if the JSON is malformed or not a service account.
 */
export function validateServiceAccount(jsonText: string): { projectId: string; clientEmail: string } {
  let obj: Record<string, unknown>;
  try {
    obj = JSON.parse(jsonText) as Record<string, unknown>;
  } catch {
    throw new Error('That is not valid JSON. Paste the full service-account key file contents.');
  }
  if (obj.type !== 'service_account') throw new Error('JSON is not a service_account key (missing "type": "service_account").');
  if (typeof obj.private_key !== 'string' || typeof obj.project_id !== 'string') {
    throw new Error('Service-account JSON is missing private_key or project_id.');
  }
  return { projectId: obj.project_id, clientEmail: typeof obj.client_email === 'string' ? obj.client_email : 'unknown' };
}

/** Render the `.env` file contents for a provider setup. Secrets included verbatim. */
export function buildEnvContent(cfg: SetupConfig): string {
  const lines = ['# ShipIT Forge — generated by `forge setup`. Keep this file secret; it is gitignored.', ''];
  switch (cfg.provider) {
    case 'vertex':
      lines.push(
        'LLM_PROVIDER=vertex',
        `VERTEX_PROJECT=${cfg.project}`,
        `VERTEX_LOCATION=${cfg.location}`,
        `VERTEX_MODEL=${cfg.model}`,
        `GOOGLE_APPLICATION_CREDENTIALS=${cfg.credentialsPath}`,
      );
      break;
    case 'anthropic':
      lines.push('LLM_PROVIDER=anthropic', `ANTHROPIC_API_KEY=${cfg.apiKey}`);
      if (cfg.model) lines.push(`ANTHROPIC_MODEL=${cfg.model}`);
      break;
    case 'openai':
      lines.push('LLM_PROVIDER=openai', `OPENAI_API_KEY=${cfg.apiKey}`);
      if (cfg.model) lines.push(`OPENAI_MODEL=${cfg.model}`);
      break;
    case 'bedrock':
      lines.push('LLM_PROVIDER=bedrock', `AWS_REGION=${cfg.region}`, `BEDROCK_MODEL_ID=${cfg.modelId}`);
      lines.push('# AWS credentials are read from the standard AWS chain (env, ~/.aws, or IAM role).');
      break;
  }
  return lines.join('\n') + '\n';
}

/** Write a file with owner-only permissions (0600), creating parent dirs. */
export async function writeSecureFile(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, { mode: 0o600 });
  await fs.chmod(filePath, 0o600).catch(() => {});
}

/** Ensure the given entries are present in .gitignore so secrets are never committed. */
export async function ensureGitignore(repoDir: string, entries: string[]): Promise<void> {
  const giPath = path.join(repoDir, '.gitignore');
  let current = '';
  try {
    current = await fs.readFile(giPath, 'utf8');
  } catch {
    /* none yet */
  }
  const have = new Set(current.split('\n').map((l) => l.trim()));
  const missing = entries.filter((e) => !have.has(e));
  if (missing.length === 0) return;
  const addition = (current.endsWith('\n') || current === '' ? '' : '\n') + missing.join('\n') + '\n';
  await fs.writeFile(giPath, current + addition);
}

/**
 * Save pasted Vertex service-account JSON to a gitignored, 0600 file inside the
 * project and return its absolute path. Validates before writing.
 */
export async function saveVertexCredential(repoDir: string, jsonText: string): Promise<{ path: string; projectId: string }> {
  const { projectId } = validateServiceAccount(jsonText);
  const dest = path.join(repoDir, '.forge', 'vertex-sa.json');
  await writeSecureFile(dest, jsonText);
  await ensureGitignore(repoDir, ['.env', '.env.*', '.forge/']);
  return { path: dest, projectId };
}

/** Interactive wizard. Used by `forge setup`. */
export async function runSetup(repoDir: string = process.cwd()): Promise<void> {
  const rl = readline.createInterface({ input: stdin, output: stdout });
  try {
    stdout.write('\n🔧 ShipIT Forge — provider setup\n\n');
    stdout.write('Which provider?\n  1) Vertex AI Gemini\n  2) Anthropic\n  3) OpenAI\n  4) AWS Bedrock\n');
    const choice = (await rl.question('> ')).trim();

    let cfg: SetupConfig;
    if (choice === '1' || choice.toLowerCase().startsWith('v')) {
      const project = (await rl.question('GCP project id: ')).trim();
      const location = (await rl.question('Location [us-central1]: ')).trim() || 'us-central1';
      const model = (await rl.question('Model [gemini-2.5-pro]: ')).trim() || 'gemini-2.5-pro';
      stdout.write('Provide the service-account key. Either:\n  • a path to the JSON file, or\n  • paste the JSON, then a line with just END\n');
      const first = (await rl.question('path or paste> ')).trim();
      let credentialsPath: string;
      let resolvedProject = project;
      if (first && !first.startsWith('{')) {
        // treat as a path; validate it
        const text = await fs.readFile(first, 'utf8');
        resolvedProject = validateServiceAccount(text).projectId || project;
        credentialsPath = path.resolve(first);
      } else {
        let buf = first;
        // continue reading until a line "END"
        // eslint-disable-next-line no-constant-condition
        while (true) {
          const line = await rl.question('');
          if (line.trim() === 'END') break;
          buf += '\n' + line;
        }
        const saved = await saveVertexCredential(repoDir, buf);
        credentialsPath = saved.path;
        resolvedProject = saved.projectId || project;
      }
      cfg = { provider: 'vertex', project: resolvedProject, location, model, credentialsPath };
    } else if (choice === '2') {
      const apiKey = (await rl.question('Anthropic API key: ')).trim();
      cfg = { provider: 'anthropic', apiKey };
    } else if (choice === '3') {
      const apiKey = (await rl.question('OpenAI API key: ')).trim();
      cfg = { provider: 'openai', apiKey };
    } else {
      const region = (await rl.question('AWS region [us-east-1]: ')).trim() || 'us-east-1';
      const modelId = (await rl.question('Bedrock model id [anthropic.claude-3-5-sonnet-20241022-v2:0]: ')).trim() || 'anthropic.claude-3-5-sonnet-20241022-v2:0';
      cfg = { provider: 'bedrock', region, modelId };
    }

    const envPath = path.join(repoDir, '.env');
    await writeSecureFile(envPath, buildEnvContent(cfg));
    await ensureGitignore(repoDir, ['.env', '.env.*', '.forge/']);
    stdout.write(`\n✅ Wrote ${envPath} (chmod 600) and updated .gitignore.\n`);
    stdout.write('   Your secrets are gitignored and will not be committed.\n');
    stdout.write(`   Provider: ${cfg.provider}. Test it: node dist/cli.js fix --repo <path> --task "..." --provider ${cfg.provider}\n\n`);
  } finally {
    rl.close();
  }
}
